### ISSUE TITLE
Hide racename from 'next_race' card

### ISSUE THREAD

**Issue by JoostAB** [marcokreeft87/formulaone-card#108]
**Is your feature request related to a problem? Please describe.**
No

**Have you tried if it is already a feature? Have you checked the wiki?**
Yes

**Describe the solution you'd like**
Option to hide race name from next_race card so I can combine it with countdown card

**Describe alternatives you've considered**
OPtion to add countdown to next_race card

**Additional context**
In response to feature request #28 from @jonathanathe you created a seperate countdown card opposed to integrating it with the next_race card. If I combine them with a vertical stack I get a duplicate rece name which looks kinda stupid ;).

![image](https://user-images.githubusercontent.com/16137715/214068361-e2d14f73-75cb-420a-90a9-f6911a48f665.png)

 If I can hide the name from the next race card this would look a lot nicer, or add an option to the next race card to show the countdown.

**Comment by marcokreeft87** [comment]
Try show_raceinfo in the countdown card. That will get you were you want to be

**Comment by JoostAB** [comment]
Great! Thx.
Maybe add that to the README?

**Comment by marcokreeft87** [comment]
It is in the readme
