### ISSUE TITLE
FEATURE REQUEST: Option to limit number of entries in the different card types.

### ISSUE THREAD

**Issue by julianrinaldi** [marcokreeft87/formulaone-card#110]
I love these cards. However they're very large. It would be nice to be able to limit the number of result entries in the different cards. For example on the results card I'd like to be able to only show the top 3 finishers. The same goes for the driver and constructor standings.

**Comment by marcokreeft87** [comment]
Hmm I think you are one of few that would like this feature. The whole point of the cards is to display the stats, and not part of the stats.

You could make the card smaller with card mod. Just hide the rows you don't want to display.

I will close this request, but if a few others request it I will realize this feature. So don't consider this as a 'won't do' but as a archive action.
