### ISSUE TITLE
FEATURE REQUEST: Show flag and team on results card

### ISSUE THREAD

**Issue by julianrinaldi** [marcokreeft87/formulaone-card#111]
I'd like to be able to show the driver flag and or team logo on the results card.

Also, on the driver standings card it would be nice to be able to just display the team logo instead of the full team name. Right now if you set the show_team to false and show_teamlogo: to true, it doesn't display the logo.

**Comment by marcokreeft87** [comment]
Sure I can make this. But keep in mind that it will take up more room, so some info will be put to 2 rows and the card will be bigger. If thats not an issue I will put it on the to do list

**Comment by FancyNerd92** [comment]
Alson Country flags on card_type: schedule will be perfect!
