### ISSUE TITLE
row_limit doesn't seem to work, but I could have done it wrong?

### ISSUE THREAD

**Issue by SuHwak** [marcokreeft87/formulaone-card#128]
**Description**
In #125 row_limit was added per my request, but I'm having a difficult time using it.

**code sample**
I've added the following card to my dashboard:
`type: custom:formulaone-card`
`card_type: constructor_standings`
`title: Constructor Standings`
`standings:`
`  show_teamlogo: true`
`  row_limit: 3`

I also tried this variant:
`type: custom:formulaone-card`
`card_type: constructor_standings`
`title: Constructor Standings`
`row_limit: 3`
`standings:`
`  show_teamlogo: true`

**Expected behavior**
I expect the card only to show the top 3 results of the constructors standing, however the card still shows the full constructor standings list. Same for the drivers standing card

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Vivaldi
 - Version: 5.6.2867.50

I am probably doing something wrong...

**Comment by SuHwak** [comment]
Huh, it now does seem to work for the driver standings card, but not yet for the constructors.

**Comment by marcokreeft87** [comment]
You are right! I forget the code in the constructors card. Let me fix that

**Comment by marcokreeft87** [comment]
should work in 0.8.2
