### ISSUE TITLE
Country flag for Austria

### ISSUE THREAD

**Issue by tcrnr1** [marcokreeft87/formulaone-card#135]
At first, this is a really cool card and I love it!
But the country flag for Austria is wrong. It should be red-white-red!

Regards from Austria
Claus-René
![proxy-image](https://user-images.githubusercontent.com/79410488/216848616-06c224ff-413d-4c16-b665-9aa996ec74fe.png)

**Comment by marcokreeft87** [comment]
Should be the correct flag now. I changed the source of the flags
