### ISSUE TITLE
Image backround color consistency

### ISSUE THREAD

**Issue by JoostAB** [marcokreeft87/formulaone-card#144]
**Describe the bug**
Backgroundcolor of track images is inconsistent

**To Reproduce**
Just put two cards with track images side-by-side
The results card (screenshot right) has a grey-ish background, whereas the previous race card is white (like the map on the countdown card). Looks like the results card is not completely transparent.

**Expected behavior**
Same color

**Screenshots**
![image](https://user-images.githubusercontent.com/16137715/217272760-5a83dd80-cf88-4b50-ae0a-fd1402ea3ce4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
 - Browser Chrome 109.0.5414.120

Looks like this is caused by the alternating row color of the table. Here, the image is the second row.

**Comment by marcokreeft87** [comment]
I didnt forget about this @JoostAB. Just a little bit busy atm

**Comment by JoostAB** [comment]
:D No whorries. It's not the end of the world. If I had time I would have fixed it myself and created a pull request.
I think if you you pull the image and the dropdowns out of the table it is solved. And do the same for the last race card for consistency.

**Comment by marcokreeft87** [comment]
Check out v1.0.3

**Comment by JoostAB** [comment]
Looks great! Thx.
I was trying another aproach myself, although it looked much the same. I was also splitting the table in two, but all header information (race selection and image) in one table without alternating rows. But this works too :)

Closing as solved
