### ISSUE TITLE
Feature on driver standings

### ISSUE THREAD

**Issue by aleZZ2001** [marcokreeft87/formulaone-card#151]
Add the ability to show only the first 10 or any other number in driver standings

**Comment by marcokreeft87** [comment]
Please check the Readme. This functionality is already implemented

**Comment by aleZZ2001** [comment]
> Please check the Readme. This functionality is already implemented

the readme says nothing about it

**Comment by marcokreeft87** [comment]
Ah I see this is lost in merging. But you are searching for : row_limit

I've added it to the readme :)
