### ISSUE TITLE
Not loading on Fire tablet with Fully Kiosk browser

### ISSUE THREAD

**Issue by billytkid** [marcokreeft87/formulaone-card#152]
Firstly, amazing work on this its great! On my laptop it works perfectly.

Sadly however its stuck as loading on the fire tablet thats running fully kiosk browser - screenshot below ([https://ibb.co/cvNxQs0](https://ibb.co/cvNxQs0))

Any ideas?

thx

**Comment by marcokreeft87** [comment]
Can you open developer tools on the tablet? Probably got something to do with the browser or maybe it can't make the requests because its blocked

**Comment by billytkid** [comment]
Aha, that's it. The tablet is blocked from the internet, I wasnt sure if the requests were coming from the HA server or not.

Will unblock and give it another go

thanks

**Comment by marcokreeft87** [comment]
Glad you found it!
