### ISSUE TITLE
date_locale returning incorrect data

### ISSUE THREAD

**Issue by andrewcalvin** [marcokreeft87/formulaone-card#153]
If date_locale is set to "au" then the date returned is mm/dd/yy, which is incorrect for au. Australia uses day month year in every format.

For example, if I use "nl" then for Bahrain (at the time of writing) then I correctly see 06/03/23. If I set it to "au" then it returns "03/06/23" which is incorrect for Australia. 

If "au" is not a valid option, then please provide a list of valid options. 

PS thank you very much for the project - it's excellent.

**Comment by marcokreeft87** [comment]
If you don't pass the locale to the card it takes your locale of home assistant. The options you have are listed here https://www.w3.org/International/O-charset-lang.html
