### ISSUE TITLE
Hide track map on results card

### ISSUE THREAD

**Issue by rasssta** [marcokreeft87/formulaone-card#154]
**Is your feature request related to a problem? Please describe.**
I'm not interested in seeing the track map and DRS zones etc. when looking through something that occurred in the past, but I like the track map feature on the next race card as it gives more detail about what's to come (and also during the race).

**Have you tried if it is already a feature? Have you checked the wiki?**
I've looked through the README but couldn't find anything that works.

**Describe the solution you'd like**
To be able to hide track map from the results card. 

**Describe alternatives you've considered**
A configuration option such as: "show_track: false"

**Comment by marcokreeft87** [comment]
Check out the latest version :)

**Comment by rasssta** [comment]
Amazing! Thanks a lot! :)
