### ISSUE TITLE
Countdown card with tracklayout

### ISSUE THREAD

**Issue by Dynamix72** [marcokreeft87/formulaone-card#156]
**Describe request**
It would be nice to have the tracklayout as an option with the countdown card.
Or a seperated card for tracklayout.

**Screenshot**
![image](https://user-images.githubusercontent.com/84641372/219949250-d8a06cfa-0dd4-475e-ac63-456faab822f7.png)

**Comment by marcokreeft87** [comment]
The countdown card already has this feature
```

show_raceinfo: true

```

It's in the readme..

**Comment by Dynamix72** [comment]
With raceinfo you get the race data as well. I just wanted the tracklayout.

**Comment by marcokreeft87** [comment]
Ah ok. Lets see what I can do for you :)

**Comment by marcokreeft87** [comment]
Check out v1.0.3

**Comment by Dynamix72** [comment]
Yes!! Many thanks!
