### ISSUE TITLE
Countdown to Qualifying

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#161]
The actual countdown only shows time till race but I want to know how long it takes to next qualifying

**Comment by snp88** [comment]
Or countdown to next event of race weekend like training etc.

**Comment by marcokreeft87** [comment]
@snp88  @superpower10 checkout the latest release :)

**Comment by snp88** [comment]
@marcokreeft87  

is this correct configuration for this ?

type: custom:formulaone-card
card_type: countdown
f1_font: true
_**countdown_type: race,qualifying,practice1,practice2,practice3,sprint**_

**Comment by marcokreeft87** [comment]
No you have to choose one
