### ISSUE TITLE
Show Date and Time of Countdown

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#168]
At the moment you can see the countdown and have the option to show all dates and times of that race weekend or nothing.

I want to see only the date and time of that special countdown.

E.g.
Countdown till qualifying plus date and time of qualifying:
2d 5h 2m 20s and Sat. 2023-03-04 at 16:00 h

**Comment by marcokreeft87** [comment]
If you set show_raceinfo to true it will show the date and times like you said. You know to what event its counting down to right? 
Maybe if more people will ask for this feature I will implement it. But for now it's going on the "maybe" list

**Comment by marcokreeft87** [comment]
After 3 weeks no one else requested this. So for now I will close this. It will reopen when someone requests it
