### ISSUE TITLE
Next_race card pic bug

### ISSUE THREAD

**Issue by Art3mis0940** [marcokreeft87/formulaone-card#169]
There is a bugged image for track

![image](https://user-images.githubusercontent.com/98536934/222695389-1198ea4e-a34f-4e3e-bdf7-a89b32df915d.png)

It appears in homeassistant mobile app and browser on desktop (i am using Vivaldi).

**Comment by marcokreeft87** [comment]
Is this link working? https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png.transform/7col/image.png

**Comment by Art3mis0940** [comment]
Nope. "Something went wrong"

**Comment by marcokreeft87** [comment]
Can you go to https://www.formula1.com/ ?

**Comment by Art3mis0940** [comment]
Nope. 403 err

**Comment by marcokreeft87** [comment]
Yes thats an issue on your network allright. Can't help you with that unfortunately.

**Comment by Art3mis0940** [comment]
I think so. With vpn it works correctly. I think its better to store pictures of tracks locally.

**Comment by marcokreeft87** [comment]
> I think so. With vpn it works correctly. I think its better to store pictures of tracks locally.

I agree, but a plugin with all images included would be too big. Plus layouts of circuits change, that way I have to update the images every time something changes. Better to not block URLs
