### ISSUE TITLE
Flags and teams

### ISSUE THREAD

**Issue by BebeMischa** [marcokreeft87/formulaone-card#17]
**Is your feature request related to a problem? Please describe.**
No

**Have you tried if it is already a feature? Have you checked the wiki?**
Yes

**Describe the solution you'd like**
As a feature request, could you include teamnames and flags in the driver standings?

**Describe alternatives you've considered**
None

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/73079275/198906041-4dfff7db-9d6e-4f9e-8660-eaf597d35965.png)

Thank you very much in advance ;-)

**Comment by marcokreeft87** [comment]
Fixed in version https://github.com/marcokreeft87/formulaone-card/releases/tag/0.1.3

**Comment by BebeMischa** [comment]
Your are lightning fast! Thank you, Marco ;-)
