### ISSUE TITLE
card_type: qualifying_results doesn‘t work

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#170]
### **I tried:**
type: custom:formulaone-card
card_type: qualifying_result

### **And this:**
type: custom:formulaone-card
card_type: qualifying_results

### **Both return errors and no results:**
TypeError: undefined is not an object (evaluating 'this.card.render')

Is that a bug or am I doing something wrong?

**Comment by marcokreeft87** [comment]
Thats because it doesnt exist. Apparently the readme was not updated. Its all in the results card

**Comment by superpower10** [comment]
Than why doesn‘t it show the result of the qualifying from today (Bahrain):
![E4DAD74D-B453-4436-9FE5-59566E50D562](https://user-images.githubusercontent.com/20533966/222919033-85d013e0-6515-40bc-a0e4-9d40abf859ea.jpeg)
