### ISSUE TITLE
Why doesn‘t it show the result of the qualifying from today (Bahrain)?

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#171]
Why doesn‘t it show the result of the qualifying from today (Bahrain)?

![FB835B36-2C7A-4871-A8C6-7C428B7114CD](https://user-images.githubusercontent.com/20533966/222919393-99a74d84-3010-4d3d-85fb-061201435edc.jpeg)

**Comment by marcokreeft87** [comment]
Because it's not available yet

**Comment by superpower10** [comment]
Oh yes. The results of the qualifying are there. Shortly after it.

See here:
https://www.formula1.com/en/results.html/2023/races/1141/bahrain/qualifying.html

**Comment by marcokreeft87** [comment]
Not on the api I use

**Comment by marcokreeft87** [comment]
But I can try to switch to another source. But that will take some time. I hope to realise it coming week

**Comment by superpower10** [comment]
@marcokreeft87 
Thank you very much.

Because the Qulifying Results are mostly interesting right after Qualifying and **before** the Race. 😊
