### ISSUE TITLE
Qualifying Countdown Text irritating

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#172]
Countdown Card shows…

![4AABEFF4-3C77-41D3-AACA-FD4082B85F67](https://user-images.githubusercontent.com/20533966/222920129-d565dea1-f264-4949-bd8a-97cc84508521.jpeg)

… even the qualifying is over.

Shouldn‘t it say:
„Qulifying is over“ 

And after race is over:
Countdown to next qualifying

**Comment by marcokreeft87** [comment]
I've added support for multiple countdown types. Hope this helps :)
