### ISSUE TITLE
Old points

### ISSUE THREAD

**Issue by snp88** [marcokreeft87/formulaone-card#173]
**Describe the bug**
After first race card drive standing and constructor standing show points from last season

**To Reproduce**

**Expected behavior**
Actual points from actual season 
**Screenshots**
![Screenshot_2023-03-06-02-12-09-317_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/46537540/222998300-422358be-132d-4a96-aaf5-415c2ee58f1b.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcokreeft87** [comment]
They are cached for 24 hours.
