### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by tonygentry** [marcokreeft87/formulaone-card#177]
Would it be possible to have Date formats match that of the local system or be user definable?

Alturnatively, would you be able to advise how I might be able to amend my instance please? Ideally I'd like DD-MMM-YY

Thank you.

**Comment by marcokreeft87** [comment]
It is already taking the formatting from Home Assistant by default.

**Comment by tonygentry** [comment]
You're a star. Thank you for your time and patience :)

**Comment by tonygentry** [comment]
Top job, thank you
