### ISSUE TITLE
Images don't load on the mac app

### ISSUE THREAD

**Issue by lo97** [marcokreeft87/formulaone-card#181]
All the track images don't load on the mac companion app. They work fine while using firefox.
Companion app version: 2023.3 (2023.451)

<img width="517" alt="Screenshot 2023-03-13 at 03 58 12" src="https://user-images.githubusercontent.com/56902258/224598236-f83feeeb-7cc0-4e51-ae4d-ff6220a626b4.png">

**Comment by marcokreeft87** [comment]
The problem probably is on the device. You are not the first to report this and every time the problem was something with firewall or VPN or something like that. I can assure you the image works. I'm afraid I can't help you with this

**Comment by lo97** [comment]
On the same device it works fine in Firefox and i don't have a VPN or firewall. Can't it be that it breaks with the MacOs app?

**Comment by marcokreeft87** [comment]
Maybe there are some settings that are enabled on the mac version of the app. I don't have Apple devices so I can't test that but I would have got more complaints about it if that was the issue.

**Comment by lo97** [comment]
It works on Safari and it works on Firefox. The app doesn't have any setting for images or cache. It's really strange that the only thing it blocks are the track images

**Comment by marcokreeft87** [comment]
I really have no idea than. Sound like something network related. Maybe try a Apple forum?

**Comment by lo97** [comment]
They found out that the app doesn't support AVIF image formats. If the request stops supporting 'image/avif' it returns a webp image and renders correctly

https://github.com/home-assistant/iOS/issues/2326#issuecomment-1485510958
https://github.com/home-assistant/iOS/issues/2326#issuecomment-1485526178

**Comment by mirekmal** [comment]
it is not just AVIF problem, I have the same issue with jpg and png. Pictures load fine in Safari and Chrome. Partially works in iOS app,. I can't figure out why, as I do not see consistency (e.g. som pictures from the same folder (\www, mapped as \local) loads OK. I have this issue in picture-elements card and also in device tracker iocons on map (some shows, some not). Clearing front end cache or reloading page does not help.
