### ISSUE TITLE
restcountries API server down

### ISSUE THREAD

**Issue by p1lh4** [marcokreeft87/formulaone-card#187]
Impossibility of loading cards due to the unavailability of the restcountries service.

Suggestions:
1. Alternative method to display the information;
2. Handling to display alert that the service is unavailable and will be back soon.
![Screenshot_1](https://user-images.githubusercontent.com/7400002/225905228-55053ec1-da0f-40f5-b552-fa11eb45c504.png)

**Comment by p1lh4** [comment]
I am getting status code 503 with cors alert.

I don't think it's an environmental issue. Other users reported service outages directly in the repository by calling https://github.com/apilayer/restcountries/issues/289

![Screenshot_2](https://user-images.githubusercontent.com/7400002/225916816-6cdbd353-786e-4cfb-829b-77851f30d791.png)
![Screenshot_3](https://user-images.githubusercontent.com/7400002/225917171-a377e2af-7a28-43db-8424-f8c9cfdcbe52.png)

**Comment by marcokreeft87** [comment]
Ah nvm, I got confused with the other API (Weather ). I can't fix this this weekend unfortunately. Hope the API will be back online soon

**Comment by amatosg** [comment]
I fixed the issue. I resized the server with twice the memory. I hope this fixes the issue. Bare in mind that the repository is not the one with API Layer.

**Comment by p1lh4** [comment]
> I fixed the issue. I resized the server with twice the memory. I hope this fixes the issue. Bare in mind that the repository is not the one with API Layer.

Thank you @amatosg 

@marcokreeft87 I suggest to evaluate the viability of adding a state treatment to the external APIs, in order to present a friendly return to the user at the interface level when they are offline.

**Comment by amatosg** [comment]
and you could also filter the fields you actually need from the country API using `?fields=name,capital,something` to reduce the response time
