### ISSUE TITLE
BR: Hiding previous races is applied after row_limit instead of vice versa

### ISSUE THREAD

**Issue by rasssta** [marcokreeft87/formulaone-card#204]
**Describe the bug**
I have configured the schedule card with "row_limit: 5" and "previous_race: hide" and I was expecting it to show the upcoming 5 races but it only shows the upcoming 3 races. It seems as the row_limit is applied *before* the removal of the previous races.

**To Reproduce**
Create this card:

type: custom:formulaone-card
card_type: schedule
title: ''
date_locale: sv
f1_font: true
row_limit: 5
previous_race: hide

**Expected behavior**
In this case where 2 races have occured in the season I'm expecting the card to show race 3-7 instead of race 3-5.

**Screenshots**
![image](https://user-images.githubusercontent.com/4455235/228230009-bdc9587c-9d4a-4a17-8a28-3e3f34a65295.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 111.0.1

Thanks again for a great card and amazing support!

**Comment by marcokreeft87** [comment]
Should be fixed now

**Comment by rasssta** [comment]
Works like a charm, thanks!
