### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by madtraxx18** [marcokreeft87/formulaone-card#22]
Downloaded and installed the latest version as the next race wasn't showing:

copied file to:

config/www

doublechecked the configuration.yaml for:

lovelace:
  resources:
    - url: /local/formulaone-card.js
      type: module

Even added the .js file as a card (sources through cards)

this is the result:

**custom element doesn't exist formulaone-card.**

type: custom:formulaone-card
card_type: next_race
sensor: sensor.formula_one_sensor_races
title: Next Race
date_locale: nl
image_clickable: false

I see the following in the logs:

2022-11-01 20:43:18.274 ERROR (MainThread) [frontend.js.latest.202209072] http://homeassistant.local:8123/local/formulaone-card.js:8:1 Uncaught SyntaxError: Unexpected token '<'

Have tried to restore an older version of the .js file and rebooted HA several times, doesn't seem to help either.

How can I install the integration using HACS and where is it listed?

**Comment by marcokreeft87** [comment]
If an older version doesnt work the problem is with your local files. Nothing I can help you with :(

**Comment by madtraxx18** [comment]
yeah seems logical, but any explanation on how to install it through HACS? that would help out a lot!

**Comment by marcokreeft87** [comment]
The only way I can explain is in the readme

**Comment by marcokreeft87** [comment]
If you add https://github.com/marcokreeft87/formulaone-card to custom repos in HACS you should find the card.

**Comment by madtraxx18** [comment]
Hmmm found the issue, cache.... damn it....

delete the cache reinstalled everything and got it working again (with the flags!!)

For the HACS part, i've now added your github page as a repository and that allowed to install it using HACS.
Didn't find this anywhere in the readme file.

Thanks for a great effort, really like the flags and teams addition!

**Comment by marcokreeft87** [comment]
Yeah cache is a ****. HACS used to clear it for you when you update or install a repo, but not anymore. I have a pull request open to make the card findable in HACS but they are super slow with reviewing.

**Comment by madtraxx18** [comment]
yeah especially if it just f*cks up an entire card, had the same thing happening with the Miflora plant status card (should have dug deeper in my memory) :-)

**Comment by marcokreeft87** [comment]
Oh well, you made it work right?

**Comment by madtraxx18** [comment]
yeah right :-D
