### ISSUE TITLE
date_locale only applying to date, not time

### ISSUE THREAD

**Issue by MadWalnut** [marcokreeft87/formulaone-card#223]
I am using this YAML:

```
type: custom:formulaone-card
card_type: next_race
title: null
f1_font: true
date_locale: de
```

`date_locale` works on the date, but not the time:

![image](https://user-images.githubusercontent.com/33835479/232595103-4ddacf77-85f7-43dc-bfd3-4f76a40b8282.png)

It should be showing the 24h clock format and not AM/PM times. When switching the `date_locale` the date changes accordingly (I tried e.g. `nl`, `da`, `de`, `cs`). But no matter what locale I set, the time format never changes.

I'm guessing this has something to do with the browser / app language. I see the wrong 12h format on both my desktop (Firefox + Windows 11 set to UK-English) and my phone (iPhone also UK-English). But if I try on a Pixel phone (set to German language) the clock format is 24h as expected.

So probably this is the cause. However `date_locale` should be overwriting these defaults also on the time and not only on the date.

**Comment by marcokreeft87** [comment]
It uses the same function as HA does. So I'm guessing de isn't a correct date locale. But if you set your HA settings correct it will by default take that settings

**Comment by MadWalnut** [comment]
Thanks for the pointer, when setting the Time Format default in my profile settings it works. Not a real problem then for most people I think, but nevertheless weird that it doesn't work without using the global HA setting.

**Comment by marcokreeft87** [comment]
Yeah don't know if it's a bug, I will research it tomorrow

**Comment by MadWalnut** [comment]
No rush at all, pretty minor issue.

**Comment by marcokreeft87** [comment]
Still haven't found a solution for it :(

**Comment by MadWalnut** [comment]
Don't worry about it, for me the workaround from above works perfectly fine. We can also close this issue if you prefer, since I seem to be the only one who noticed this anyway.

**Comment by marcokreeft87** [comment]
Ok let's do that and reopen it when needed

**Comment by marcokreeft87** [comment]
Yes let's keep an eye on it and report back here after daylight savings
