### ISSUE TITLE
new rules for sprints

### ISSUE THREAD

**Issue by Santanachia** [marcokreeft87/formulaone-card#224]
The FIA has introduced new rules regarding qualifying for races with sprints. The sprint will have separate qualifying and the race will have separate qualifying.
![image](https://user-images.githubusercontent.com/4628507/234853726-38c2b0b3-4f8b-4ea6-98dd-a3fa111d015b.png)
![image](https://user-images.githubusercontent.com/4628507/234854558-4d9acf32-a810-4710-96d5-7f017452ac97.png)

![image](https://user-images.githubusercontent.com/4628507/234853874-56afc049-14cb-412b-b3c3-e51ba4528a11.png)

**Comment by marcokreeft87** [comment]
I use a external API. And I cant change this unless the API changes. So when that happens I will try to update the card asap

**Comment by marcokreeft87** [comment]
Nah, If I fix it, I'm doing it correctly

**Comment by MauriceW67** [comment]
The time is wrong as well. Sprint Shootout is at 10:30 CET on Saturday.

**Comment by marcokreeft87** [comment]
> The time is wrong as well. Sprint Shootout is at 10:30 CET on Saturday.

That would be your settings ;)

**Comment by marcokreeft87** [comment]
You are right. It seems the api is passing the wrong times. But not for the race and sprint tho.. weird

**Comment by marcokreeft87** [comment]
Looks like it's a known issue. We have to wait for the api to fix that

**Comment by Ascathon** [comment]
> You are right. It seems the api is passing the wrong times. But not for the race and sprint tho.. weird

Probably same reason as it isn't called shootout yet. Start moved 1 hour earlier. But if it is a known issue, we'll wait. Nothing you can change.

**Comment by marcokreeft87** [comment]
Since the API will be depricated ( starting 2025), this won't be fixed I guess. I'll close this issue and hope there will be a new API

**Comment by Santanachia** [comment]
we still have 2 years of working APIs as it is. Please consider making a change on the integration side as it is trivial to distinguish whether there will be a sprint or not.

**Comment by marcokreeft87** [comment]
If you know where to get the data from? The data comes from the api

**Comment by Santanachia** [comment]
Just check if there is a date for the third practice. If there is = normal weekend; If there is not = sprint weekend.

**Comment by marcokreeft87** [comment]
That's not how it works, and that will break when there will be a change in the data (like now)

**Comment by Santanachia** [comment]
Sprint weekends are already broken. You can leave it as it is = broken, or make it work better.

**Comment by redlegoman** [comment]
> Sprint weekends are already broken. You can leave it as it is = broken, or make it work better.

or you could make it better. 
chill, this is free, and @marcokreeft87 doesn't work for you.

**Comment by Santanachia** [comment]
I could if I knew this programming language.
 Unfortunately I do not know.

 I know there is an error and I am reporting it.  I also see that it can be repaired and I don't understand why there is so much reluctance to fix something that is broken.

**Comment by redlegoman** [comment]
> I could if I knew this programming language. Unfortunately I do not know.
> 
> I know there is an error and I am reporting it. I also see that it can be repaired and I don't understand why there is so much reluctance to fix something that is broken.

the point is, you're behaving as if you are entitled to a fix. you're not paying for anything, you can't demand it be fixed. you could try being a little more polite and grateful that the author decided to share his work. he could quite easily keep it just for himself.
