### ISSUE TITLE
Track Image Not Loading

### ISSUE THREAD

**Issue by DanielGroot** [marcokreeft87/formulaone-card#23]
For some reason my track image isn't showing in my card. Is this a current bug? ![image](https://user-images.githubusercontent.com/70161891/201655221-3e9d6472-78cc-4a77-ab2e-e0192ec14f73.png)

**Comment by marcokreeft87** [comment]
@DanielGroot this should be fixed in 0.1.4

**Comment by DanielGroot** [comment]
Yup! You're amazing ![image](https://user-images.githubusercontent.com/70161891/201774986-db9eee66-c4ff-4aa9-ab77-b0b5be3b9566.png)
