### ISSUE TITLE
Error getting ...

### ISSUE THREAD

**Issue by jarube** [marcokreeft87/formulaone-card#230]
**Describe the bug**
all cards show error message. for instance "!Error getting Next Race!" or "!Error getting standings!"

**To Reproduce**
NA

**Expected behavior**
Cards to be shown as it always did

**Screenshots**
![image](https://user-images.githubusercontent.com/92972738/235458612-166665a4-110b-4f14-b182-741168a64990.png)

**Additional context**
Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend-versie: 20230411.1 - latest

**Comment by marcokreeft87** [comment]
Your computer cannot reach the API. Do you have VPN running? 
Can you reach this url? https://ergast.com/api/f1/2008/5/results.json

**Comment by jarube** [comment]
No clue what happened, but somehow everything is working now. I did restart HA, but that did not fixed it. But now it does.
my apologies.... I have no VPN, HA runs in VMWARE on a NUC.

**Comment by jarube** [comment]
Hi, found the source of the problem. The switch connected with the NUC did reboot itself about 45 min ago… no clue why, but should have caused the issue.

**Comment by marcokreeft87** [comment]
No worries, glad its working now :)
