### ISSUE TITLE
Split race info and agenda

### ISSUE THREAD

**Issue by woempiej** [marcokreeft87/formulaone-card#233]
Hi and hello,

Is is possible to split the info for the next race in 2 chapters like below?

![afbeelding](https://user-images.githubusercontent.com/62903344/236639295-29398aa6-cb65-478f-a663-4f687078728a.png)

**Comment by marcokreeft87** [comment]
The card would be too big imo

**Comment by woempiej** [comment]
Yes, the layout is great this way but can you for example break the grey lines in the middle?

![afbeelding](https://user-images.githubusercontent.com/62903344/236639715-17557c5f-de1b-4418-b12f-f92723e9fbc9.png)
