### ISSUE TITLE
Delay x hours before switching to next race

### ISSUE THREAD

**Issue by CaptainKarma** [marcokreeft87/formulaone-card#236]
**Is your feature request related to a problem? Please describe.**
I rarely watch the races live and the card jumps to the next race immediately after the race has finished.

**Have you tried if it is already a feature? Have you checked the wiki?**
Yep and couldn't see a delay option

**Describe the solution you'd like**
Delay switching to the next race as soon as its finished by the specified number of hours

**Comment by marcokreeft87** [comment]
I'm gonna make it configurable

**Comment by marcokreeft87** [comment]
To be sure. Which card are you talking about?

**Comment by CaptainKarma** [comment]
Hi, I'm using the "next_race" card, thanks

**Comment by marcokreeft87** [comment]
You should be able to do it with the latest version
