### ISSUE TITLE
Last Result Card showing incorrect grid number

### ISSUE THREAD

**Issue by MagieMalone** [marcokreeft87/formulaone-card#240]
**Describe the bug**
Miami race result shows Max as grid number 0, his real grid number (9) is also missing in the list

**To Reproduce**
load the last results card 

**Expected behavior**
expected grid postion to be 9

**Screenshots**
<img width="364" alt="image" src="https://github.com/marcokreeft87/formulaone-card/assets/19596127/bf9813a9-8505-4df7-834f-a78b3b58818d">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 113.0.5672.93 (Official Build) (64-bit)

**Additional context**
```
type: custom:formulaone-card
card_type: last_result
title: Last Result
f1_font: true
hide_tracklayout: true
```

**Comment by marcokreeft87** [comment]
Already reported. The API reports the wrong grid starting position. Out of my hands

**Comment by MagieMalone** [comment]
ah, I'm sorry, didn't check closed issues, my bad.
