### ISSUE TITLE
Country API is down, so flags are not available at the moment!

### ISSUE THREAD

**Issue by revalutionzzz** [marcokreeft87/formulaone-card#243]
**Describe the bug**
Just followed guidance for this repo in GitHub and running latest build of HA, HACS and formulaone-card.
When creating the card I am getting the error "Country API is down, so flags are not available at the moment!" and not displaying most of the information that is shown in the examples on GitHub (i.e Track maps, next race info and times etc.).

**To Reproduce**
Not too sure if this is a temporary API issue or if I have missed something along the way.

**Screenshots**
Screenshot of dash below.
<img width="756" alt="Screenshot 2023-05-28 122708" src="https://github.com/marcokreeft87/formulaone-card/assets/9106616/648d56df-9082-4ecb-a756-e7b1aece1f9e">

**Additional context**
Not running an overly complex HA setup so not a lot in the way that could conflict, I have carefully gone back through the guidance for this card and pretty sure I have not missed anything, used the YAML config method but have also tried manual to rule that out too. (removed any changes made during the manual setup).

Any help will be greatly appreciated.

**Comment by marcokreeft87** [comment]
Check if you can reach  'https://restcountries.com/v2 if that doesn't work you got a network issue

**Comment by revalutionzzz** [comment]
Thank you for the quick response, yeah it looks like that site is down? Just tried from another device not connected to my network and get the same error.
<img width="666" alt="image" src="https://github.com/marcokreeft87/formulaone-card/assets/9106616/1cdede93-64b2-48e2-b844-29765d138f2f">

**Comment by marcokreeft87** [comment]
Hmm than you will have to wait unfortunately
