### ISSUE TITLE
Error getting race data

### ISSUE THREAD

**Issue by canedje** [marcokreeft87/formulaone-card#244]
**Describe the bug**
The card is not reading data anymore
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/marcokreeft87/formulaone-card/assets/23150947/7b200fd2-bd99-4a50-94d4-7b56ac05f1f9)

**Desktop (please complete the following information):**
 - OS: windows/android/IOS
 - Browser chrome, safari
 - Version 1.6.0

**Smartphone (please complete the following information):**
 - Device: iPad/ samsung phone
 - OS: [e.g. iPadOS16.5
 - Browser safari
 - Version 1.6.0

**Additional context**

**Comment by canedje** [comment]
That’s a pity. Thanks

**Comment by RGlintmeijer** [comment]
Seems like the API is currently not working using HTTPS, only HTTP. I've added a bugreport to http://ergast.com/mrd/bugs/ to (hopefully) inform the admin.

**Comment by hmmbob** [comment]
It's a server-side error, the ssl certificate chain is incomplete. Only the server admin can fix this.
