### ISSUE TITLE
all in one countdown 

### ISSUE THREAD

**Issue by trackermb** [marcokreeft87/formulaone-card#245]
HI this may all ready be possible but i havent been able to find it.  I currently have multiple countdown timers as per below
<img width="1349" alt="image" src="https://github.com/marcokreeft87/formulaone-card/assets/7849892/f974e702-0783-4e03-a1cb-23ab7d98e68a">

What im looking for is an all in one countdown that starts at practice 1 and then once thats started moves on to practice 2, then 3 then qualifying and finally the race.

If this is currently possible could you please provide me with the countdown_type: 

Many Thanks

**Comment by marcokreeft87** [comment]
You can do it like this

```
type: custom:formulaone-card
card_type: countdown
date_locale: nl
f1_font: true
countdown_type:
  - race
  - qualifying
  - sprint
```
