### ISSUE TITLE
No image for Abu Dhabi Circuit

### ISSUE THREAD

**Issue by Damazinho** [marcokreeft87/formulaone-card#25]
The image for the Abu Dhabi circuit is not available, the link to show  it is not correct.

**Comment by marcokreeft87** [comment]
If you use the latest version it is working. Confirmed by multiple users

**Comment by Damazinho** [comment]
It worked for a few hours with the latest version, but now it disappeared again?

**Comment by marcokreeft87** [comment]
Did you clear your cache?

**Comment by Damazinho** [comment]
Offcourse

**Comment by marcokreeft87** [comment]
Sounds like a caching issue. It's working here so idk man

**Comment by EvertJob** [comment]
Same issue, cleared cache and same issue with private browser

**Comment by marcokreeft87** [comment]
Sounds like you dont have the latest version, do you guys have v0.1.4 ?

**Comment by Damazinho** [comment]
Yes, it was solved few hours ago but problem came back

**Comment by marcokreeft87** [comment]
Than I cant help you with this problem. Sorry, but if I can reproduce, I cant fix

**Comment by EvertJob** [comment]
It's getting the image from this URL: https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/UAE_Circuit.png.transform/7col/image.png

And that does not exists so it looks like a missing map on the F1 website.

**Comment by EvertJob** [comment]
After reinstalling the Lovelace card the issue is fixed. Sent from my iPhoneOn 18 Nov 2022, at 15:30, Marco Kreeft ***@***.***> wrote:﻿
Thats exactly what I fixed in v0.1.4 compare to 0.1.3.

**Comment by marcokreeft87** [comment]
@Damazinho So cache is the issue! Something changed in HACS, now when you update a card the cache doesnt get refreshed. It used to do that for you.
