### ISSUE TITLE
[Feature Request] Race weekend dates in lieu of Countdown?

### ISSUE THREAD

**Issue by Joshndroid** [marcokreeft87/formulaone-card#265]
Fantastic card 1stly.

I was wondering if there was the ability to just have the date of the race weekend instead of an active countdown?
I have had a look in the toggles, etc and it appears that its merely just an on/off
I have a card that I use which is for a different sport, and like the cleanness of having just the team picture and the date of the next game/etc.
I was hoping to recreate this with the track image and the date of the next race weekend (i guess whatever the countdown actually counts down too)
The race information is quite bulky, nice to have in a separate F1 card (which is what I have setup) but i like my home default card to be as sleek and to the point as possible, hence the suggestion/request
This could work like an on/off toggle much like the countdown timer.

**Comment by marcokreeft87** [comment]
Take a look at countdown_type in the documentation :)

**Comment by Joshndroid** [comment]
This will still provide just a countdown.
What I was hoping for is for it to just provide a 'date' in that countdown section
so instead of 27D 16H....
It would just say the date&time like 26th August 2023 3pm

**Comment by marcokreeft87** [comment]
Oh right. You are look for the next_race card I guess?

**Comment by Joshndroid** [comment]
Yeah but I find that the next race card information is huge with every bit about the race weekend. That is great for a dedicated card but as a quick home tab card it would be nicer to have just the race weekend date/time as a single line and the track

**Comment by marcokreeft87** [comment]
Hmm I don't see the added value for it right now. But it will go on the to do list if more people ask for it.

For now, you could use this sensor :
https://community.home-assistant.io/t/formula-one-card/476902/91?u=marcokreeft87

And show that value in a card?

**Comment by Joshndroid** [comment]
I was thinking that you could use a bunch of the countdown code and have it display the date instead of the countdown. This could be a toggle to apply a conversion such that it would display the countdown information or the value that the countdown timer is actually counting down too. 

You could then allow for the countdown to have a toggle for the 'track image' true/false

I will have a look and see what else is out there regarding ICS, etc. Just thought I would ask if it was going to be something somewhat easier to implement. 
Again awesome card though

**Comment by marcokreeft87** [comment]
Unfortunately it's not that easy since the card is build for the countdown right now. I also try to keep it as clean as possible so this would probably be another card. I mean if it's now counting down, it's not a countdown card right?

But if someone else asks for this I will put it on the todo list.

**Comment by marcokreeft87** [comment]
@Joshndroid I could let it go. Check out version 1.8.2 :)

**Comment by Joshndroid** [comment]
Love your work @marcokreeft87 !!
