### ISSUE TITLE
Every Update gives an error message

### ISSUE THREAD

**Issue by pjannink** [marcokreeft87/formulaone-card#273]
Every time I load my F1 submenu after I updated F1 it shows errors for several cards. Only a few cards, like "team standing" show correctly.
Reloading the submenu I created for the F1 info seems to reload whole Home Assistant: takes quite a while. The Core Log does not give any indication on why this happens.

I run the latest version of HA in Docker on Synology (everything is up2date)

**Comment by marcokreeft87** [comment]
Can you please fill in the form that's requested when you create a bug? Without more info I can't help you.

**Comment by pjannink** [comment]
**Describe the bug**
After any HACS update of F1 some items give an error message when loading the page where I put the F1 tiles. 

**To Reproduce**
1. Update F1 form via HACS
2. Visit the lovelace page with F1 information. Some tiles give "cannot load"-error. Reloading the page in the browser takes quite some time and seem to reload whole lovelace

**Expected behavior**
Loading without erors

**Screenshots**
Not available. Surely after next HACS update

**Desktop (please complete the following information):**
 - Windows 11 Pro, up2date
 - Firefox, up2date

**Smartphone (please complete the following information):**
Not sure the same happens on iOS/iPadOS - not tested yet

**Additional context**
Add any other context about the problem here.

**Comment by marcokreeft87** [comment]
Ok this info doesn't help either. Could you test on pc or tablet and provide screenshots? My best guess now is that your phone can't reach the api.

Can you go to https://ergast.com/api/f1/current.json on your phone?

**Comment by pjannink** [comment]
I will test / make screenshots with next update.Link opens well on my iPad, sh0ws a lot of XMS code :-)GrzVerstuurd vanaf mijn iPadOp 2 aug. 2023 om 18:56 heeft Marco Kreeft ***@***.***> het volgende geschreven:﻿
Ok this info doesn't help either. Could you test on pc or tablet and provide screenshots? My best guess now is that your phone can't reach the api.
Can you go to https://ergast.com/api/f1/current.json on your phone?

**Comment by marcokreeft87** [comment]
How is this coming along? I can't reproduce so my best guess is that its something on your ipad?

**Comment by marcokreeft87** [comment]
Im closing this issue since I cant reproduce and there was no response

**Comment by pjannink** [comment]
Pls find attached the messages I receive when loading the F1 page after an update. After refreshing the page, the issue is normally resolved. May be force a page refresh??[](url)
![F1 foutmelding na update](https://github.com/marcokreeft87/formulaone-card/assets/85283776/db0a48bc-a1fb-42e3-bca0-84ea40f886d0)

**Comment by pjannink** [comment]
Hi Marco,

 

Refreshing the page resolves it – I can live with it. Have you seen my comment on the tab Results where the label Grid is a bit unaligned with the data below?

 



 

Van: Marco Kreeft ***@***.***> 
Verzonden: donderdag 10 augustus 2023 09:25
Aan: marcokreeft87/formulaone-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [marcokreeft87/formulaone-card] Every Update gives an error message (Issue #273)

 

Looks like network issues. But the weird part is that the one card is working. I can't help you from here I'm afraid. But there were multiple issues with iOS devices in the past, maybe the old issues will help you find the answer?

**Comment by marcokreeft87** [comment]
Yes, I've asked you a question about it :p
