### ISSUE TITLE
Tabs in current Grand Prix

### ISSUE THREAD

**Issue by pjannink** [marcokreeft87/formulaone-card#274]
Currently the order of the tabs is: Race - Qualification - SprintRace

More logical in time sequence is the following order: Qualification - Sprintrace - Race.

For the Schedule page I would like an option to only show the remaining races in the season.

**Comment by marcokreeft87** [comment]
Maybe hiding the tab is the better fix yes. Closed the issue by accident, sorry for that, the app is different from the website.

**Comment by marcokreeft87** [comment]
I've kept the order of the tabs as is.  Now the sprint tab gets hidden when there was no sprint race.
I've kept the order of the tabs this way because most people are interested in the result of the race. Maybe I'll change it in the future so everyone can determine their own order.

Check out version 1.8.3

**Comment by marcokreeft87** [comment]
And there it is. Version 1.8.4 had the option to configure the tab order

**Comment by pjannink** [comment]
Hi Marco,

 

De tabs_order krijg ik niet werkend:

 

Bij gebruik van dubbele aanhalingstekens een rare indent fout:



 

Bij gebruik van enkele aanhalingstekens zoals je beschrijft idem dito.

 

Laat ik de aanhalingstekens weg, verdwijnt in indentation error maar toont ie een foutmelding e.map is not a function:

 



 

 

 

Hierbij de foutmeldingen na het laden van een nieuwe versie. Na een reload werkt hij wel weer.

 



 

Van: Marco Kreeft ***@***.***> 
Verzonden: zaterdag 5 augustus 2023 19:49
Aan: marcokreeft87/formulaone-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [marcokreeft87/formulaone-card] Tabs in current Grand Prix (Issue #274)

 

And there it is. Version 1.8.4 had the option to configure the tab order

**Comment by marcokreeft87** [comment]
Een array in HA geeft je aan als list items:

Dus als volgt:

- Sprint
- Results
- Qualifying


Maar dan in de volgorde die je wilt natuurlijk

**Comment by pjannink** [comment]
Top!

 

Dat werkt. Nog een kersje op de taart: de uitlijning van Grid en de getallen daaronder is niet helemaal mooi:

 



 

Voor een volgende regenachtige zondag zonder F1 race 😊

 

Groet, Paul

 

Van: Marco Kreeft ***@***.***> 
Verzonden: zondag 6 augustus 2023 11:36
Aan: marcokreeft87/formulaone-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [marcokreeft87/formulaone-card] Tabs in current Grand Prix (Issue #274)

 

Een array in HA geeft je aan als list items: 

Dus als volgt: 

- Sprint 
- Results 
- Qualifying 


Maar dan in de volgorde die je wilt natuurlijk

**Comment by marcokreeft87** [comment]
Bij welke race is dit t geval?
