### ISSUE TITLE
Request for new features: Countdown and Previous results.

### ISSUE THREAD

**Issue by jonathanathe** [marcokreeft87/formulaone-card#28]
**Is your feature request related to a problem? Please describe it ** A clear and concise description of what the problem is.
No.

**Have you checked if it is already a feature, have you looked on the wiki?
Yes.

**Describe the solution you would like**
I would like during this long wait, to be able to see the following features.

1. I don't know if it is possible but using for example the "Last result" card to have a drop down on the race name and be able to select a previous race to see these previous results.

2. I would also like a countdown of what is left for the next race. Usable to know when the next season will start and then to know when the next race is with a counter. 

This counter always if you can add the flag of the country for example.

Thanks for your attention. Regards.

**Comment by marcokreeft87** [comment]
1. is possible. I will add it to the todo list
2. Isn't possible atm, because the API I use doesnt have this data unfortunately.

**Comment by jonathanathe** [comment]
> 1. is possible. I will add it to the todo list
> 2. Isn't possible atm, because the API I use doesnt have this data unfortunately.

Thank you for your quick response. And certainly thank you for this very cool project.

**Comment by marcokreeft87** [comment]
With the new season schedule know, I could implement a countdown :) What did you have in mind? A seperate card ?

**Comment by bboerendans** [comment]
A seperate card would be great imo. In that case we can just add it to the same tab as the next race.

**Comment by jonathanathe** [comment]
> With the new season schedule know, I could implement a countdown :) What did you have in mind? A seperate card ?

I had thought of a small simple windget card that is the name of the next race and the countdown.

Here is a small outline I made so that you have an idea of what you had thought and give me your opinion.

![image](https://user-images.githubusercontent.com/34164094/210649671-3016ce1e-1b70-4fe6-9a9e-bef6a55f9998.jpeg)

Thanks!

**Comment by marcokreeft87** [comment]
Ok let me first get the tests working again. After that I will create this :)

**Comment by marcokreeft87** [comment]
OK so only the countdown card to go :)

**Comment by marcokreeft87** [comment]
Countdown card added :) @jonathanathe

**Comment by jonathanathe** [comment]
> Countdown card added :) @jonathanathe

I am looking forward to the update in HACS to be able to download the!

Thank you very much for your work!
