### ISSUE TITLE
After migration from Rpi3 to a new Rpi4 the dashboard shows only errors

### ISSUE THREAD

**Issue by Rood75** [marcokreeft87/formulaone-card#285]
The migration to Rpi4 has been successfully completed except for the Lovelace dashboard.

The configuration is in:
![image](https://github.com/marcokreeft87/formulaone-card/assets/119455326/8c603c2e-f4f6-45ed-a889-5e8c108c4317)

I have already removed and re-added the add-on once which made no difference:
![image](https://github.com/marcokreeft87/formulaone-card/assets/119455326/2cb54bf5-9929-41cb-a3a4-deb0fe3d9f7d)

**Comment by marcokreeft87** [comment]
There was an error on the api server. Should be working now?

**Comment by Rood75** [comment]
Unfortunately, I still have the same problem

**Comment by marcokreeft87** [comment]
I think I have the same issue now. Will check it tonight

**Comment by Rood75** [comment]
Ok, no hurry. Just let me know when I can test again.

**Comment by euri911** [comment]
[Same here]

Funny fact:  when accessing the relevant cards in my dashboard, the HA Companion App complains that the HA certificate is invalid  :)

![Screenshot_2023-08-29-21-03-45-28_c3a231c25ed346e59462e84656a70e50](https://github.com/marcokreeft87/formulaone-card/assets/94360296/a12876b9-b826-4eca-b335-1b1b7ee74c3e)

**Comment by marcokreeft87** [comment]
Haha indeed! I noticed it too

**Comment by Rood75** [comment]
It does indeed work again. So was pure coincidence in my case.
