### ISSUE TITLE
Add cards translation

### ISSUE THREAD

**Issue by MichelJourdain** [marcokreeft87/formulaone-card#29]
**Is your feature request related to a problem? Please describe.**
No

**Have you tried if it is already a feature? Have you checked the wiki?**
Yes

**Describe the solution you'd like**

Add the ability to translate cards into a language other than English.

**Describe alternatives you've considered**
Change the code.

![2E48A199-0D93-4E70-8DB9-73E0BC248154](https://user-images.githubusercontent.com/83040228/204019178-47b53b78-c6fa-40e8-8676-d771087d482c.jpeg)

**Comment by marcokreeft87** [comment]
@MichelJourdain check out v0.2.0. Examples in the readme :)

**Comment by Fredzxda** [comment]
Version 0.2.0 allows only to translate part of the text. For exemple in the current case, "Finished" as to be translated into "Terminé"

**Comment by marcokreeft87** [comment]
Yes that's because of that text comes from the api
