### ISSUE TITLE
Next race without schedules

### ISSUE THREAD

**Issue by Danieldiazi** [marcokreeft87/formulaone-card#291]
**Describe the bug**
I don't know when, but in the beginning I had schedules in "next race" card below the circuit map. But now I can't see it.

**To Reproduce**
Put the configuration of "next race" card

`type: custom:formulaone-card
card_type: next_race
title: Next Race
date_locale: nl
image_clickable: false`

**Expected behavior**
To see schedules of next race

**Screenshots**
![imagen](https://github.com/marcokreeft87/formulaone-card/assets/3638478/cbd7bb30-2b35-4f22-88ab-83592b25db42)

I've cleared browser cache. Any ideas?

**Comment by marcokreeft87** [comment]
Try show_raceinfo: true

**Comment by Danieldiazi** [comment]
> Try show_raceinfo: true
@marcokreeft87  I see the problem, thanks, show_raceinfo is false by default.
The mistake was reading README:

![imagen](https://github.com/marcokreeft87/formulaone-card/assets/3638478/a17d864b-112d-456f-9342-e22ab4727f7a)

As you can see, the code example lacks "show_raceinfo: true" in the sample image
That's the code I've just copied.

I don't have any problem in propose this change creating a pull request in README.md in order to avoid mistakes to others.

**Comment by marcokreeft87** [comment]
It was in the release notes

**Comment by Danieldiazi** [comment]
> It was in the release notes and it's in the readme

Hi!

It only was a suggestion, you can see in README.md the screenshot that I have provided and in my opinion it can lead to confusion if a user follows this file, but it was only a suggestion without the intention of disturbing.

If that's okay for you, ok me too!

Anyway, Thanks for your great integration it's useful for me!!

**Comment by Danieldiazi** [comment]
> It was in the release notes and it's in the readme. But I'll update the example

I have seen a change in the README.md file, but I think it is not in the place we were referring to.

I can see a change in "Actions example" including "show_raceinfo: true" but In "Next Race" example, into "Example configurations" doesn't have "show_raceinfo: true".

Thanks in advance, and sorry if I'm being annoying
