### ISSUE TITLE
Tabs in race result do not work

### ISSUE THREAD

**Issue by pjannink** [marcokreeft87/formulaone-card#297]
I can not click on the tabs for showing qualify / sprint / race results. Also the icons are aligned left and not spread over de width of the column. Running HA 2023.9.2 and also up2date F1-card.

![image](https://github.com/marcokreeft87/formulaone-card/assets/85283776/95515ce4-bab9-40f9-84bf-462a24259951)

**Comment by marcokreeft87** [comment]
I had that too! But it automagically fixed itself for me. Can you try and clear your cache?

**Comment by pjannink** [comment]
After some hassle resolved too after removing the card twice.One more thing: your card says Qatar race starts at 16:00 NL time. Should be 19:00 as far as I know.the locale says “nl”.Greetings, PaulVerstuurd vanaf mijn iPadOp 3 okt 2023 om 16:18 heeft Marco Kreeft ***@***.***> het volgende geschreven:﻿
I had that too! But it automagically fixed itself for me. Can you try and clear your cache?

**Comment by marcokreeft87** [comment]
Hmm the api passes the wrong time. Nothing I can do unfortunately

**Comment by pjannink** [comment]
Issue with the tabs seems solved. I added following lines, missing in my setup after readding the results-card:
    standings:
      show_flag: true
      show_team: true
      show_teamlogo: true
Now tabs show as before and are also clickable again.

**Comment by pjannink** [comment]
But then adding the tabs_order makes it a mess again....

**Comment by marcokreeft87** [comment]
I think it's cache tbh. It's working fine on my machine but I clear the cache after every update

**Comment by marcokreeft87** [comment]
But I'll try to reproduce tonight

**Comment by marcokreeft87** [comment]
I'm not sure on how to clear the cache on iOS devices sorry. But as long I can't reproduce I can't help you. Seems like you are the only one so far having this issue
