### ISSUE TITLE
Timezone used for Qatar race is incorrect

### ISSUE THREAD

**Issue by vaibhav2912** [marcokreeft87/formulaone-card#301]
**Describe the bug**
The timezone I am in is eastern time UTC-5 but the timezone used to display race time is UTC-8 (pacific time). I don't know if this is only me. HA timezone and timezone on my PC is correct (UTC-5).

**To Reproduce**
1. Set up next_race card or countdown card.
2. See time for race on next_race card and time difference on the countdown card.

**Expected behavior**
Card is expected to use the same timezone as HA.

**Screenshots**
![image](https://github.com/marcokreeft87/formulaone-card/assets/20019445/4494532a-e726-4014-9ecc-aa000a72a0fd)
![image](https://github.com/marcokreeft87/formulaone-card/assets/20019445/31b93d28-4f30-4598-9af0-2b6228fe4a94)

**Comment by marcokreeft87** [comment]
Plz search the old issues before reporting a bug. This is a duplicate

**Comment by vaibhav2912** [comment]
I tried searching in the existing issues before I posted this but I couldn't find a similar issue reported.
Can you please point me to the issue that is a duplicate of this ?

This is the yaml I use:

> type: custom:formulaone-card
card_type: next_race
title: Next Race
image_clickable: false
show_raceinfo: true

**Comment by rossiluis22** [comment]
i'm also in the same situation, i'm not able to find anything and also tried different ways, and still wrong time this is my config:

```
type: custom:formulaone-card
card_type: countdown
show_raceinfo: true
date_locale: es
f1_font: true
```

**Comment by marcokreeft87** [comment]
It's a discussion sorry: https://github.com/marcokreeft87/formulaone-card/discussions/300

**Comment by vaibhav2912** [comment]
Thanks
