### ISSUE TITLE
Time(zone) differs per browser/app

### ISSUE THREAD

**Issue by bjornstevens** [marcokreeft87/formulaone-card#302]
**Describe the bug**

The times shown in the charts aren't the same timezone per browser (My firefox isn't in the right one, whilst my Chrome is).
My phone also shows the wrong time (in my case it is off by 3 hours).

**To Reproduce**
- Chrome shows the right one
- Home Assistant app shows the right one SOMETIMES
- Firefox doesn't
- Phone browser does

**Expected behavior**
The right times for all devices and browsers

**Screenshots**

Firefox:
![afbeelding](https://github.com/marcokreeft87/formulaone-card/assets/23235234/904de1ca-9fd5-4b04-8b26-d16e439cd0b2)

Chrome:
![afbeelding](https://github.com/marcokreeft87/formulaone-card/assets/23235234/615ac896-8086-440e-bba8-81e77fb652be)

APP at some point:
![afbeelding](https://github.com/marcokreeft87/formulaone-card/assets/23235234/4d71607c-eb49-4de3-b021-e79c5c5aaafc)

**Desktop (please complete the following information):**
Windows 10 (latest update)

**Smartphone (please complete the following information):**
Samsung S23 running latest Android version 13.
Browser: Firefox
App: Home Assistant

**Additional context**

I would like there to be just a hardcoded entry for the Timezone (optional), because it's really annoying that my times shown are 3 hours off.

**Comment by marcokreeft87** [comment]
The result of the gets cached. So apparently they fixed the time and that's why one of your devices shows the old time
