### ISSUE TITLE
Error: Please pass the correct sensor (races)

### ISSUE THREAD

**Issue by Dynamix72** [marcokreeft87/formulaone-card#31]
This minor bug is because there are no next races for this year 2022. 
I use the card type: next_race

type: custom:formulaone-card
card_type: next_race
sensor: sensor.formula_one_sensor_races
title: Next Race
date_locale: nl
image_clickable: false

The sensor (sensor.formula_one_sensor_races) has al race of 2022 but not 2023.

It's more correct to say: "Season is over. See you next year!" 
that is already implemented, if you use the card type: Schedule

**Comment by marcokreeft87** [comment]
Please create this bug in the correct repository: https://github.com/delzear/hass-formulaoneapi

**Comment by marcokreeft87** [comment]
The card already does this?

**Comment by marcokreeft87** [comment]
The card already does this

**Comment by Dynamix72** [comment]
Your right. Was a cache problem.
