### ISSUE TITLE
Las Vegas track image missing

### ISSUE THREAD

**Issue by fl380** [marcokreeft87/formulaone-card#312]
**Describe the bug**
A placeholder is visible where the track image should be displayed

**Expected behavior**
Track image has been visible for all previous races including Brazil on Sunday

**Screenshots**
![image](https://github.com/marcokreeft87/formulaone-card/assets/6693239/35c3eb66-c504-43ac-bd0b-f4b9fa8491e6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome and firefox 

**Smartphone (please complete the following information):**
 - Device: iPhone 12/Android Tablet
 - OS: iOS17.1/unknown
 - Browser HA App

**Comment by marcokreeft87** [comment]
Yes I was waiting for this issue, unfortunately I'm not going to be able to find a solution for this before the race is over. The fact is, the source of the images doesnt have the image for this because its from 2018. 

Combine this with the fact that the API is deprecated I will find a solution for this when I have a replacement for the API.
For now you could hide the tracklayout to hide the "image not found" image

**Comment by JAudi23** [comment]
I'm not a coder, but the image is available, is there no way to pull it into the integration?
https://www.formula1.com/en/racing/2023/Las_Vegas/Circuit.html

![image](https://github.com/marcokreeft87/formulaone-card/assets/107599616/bd5307b6-af2d-45ce-bfee-657e9ea9a7f5)

**Comment by bkbartk** [comment]
You could just hardcode it,
I did,
I was to lazy to write a proper escape
but that also overwrites the layout of the last GP, or any GP for that matter.
![image](https://github.com/marcokreeft87/formulaone-card/assets/17070805/2480b18f-111b-44af-aeb7-41badaaecd82)

**Comment by mrdroopy** [comment]
@marcokreeft87 the image is there in that same source: https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit.png.transform/7col/image.png so you should be able to pull it using the Las_Vegas_Circuit name.

**Comment by marcokreeft87** [comment]
v1..8.9 fixed it. Thnx @mrdroopy !

**Comment by mrdroopy** [comment]
Graag gedaan and thanks to you for the quick fix @marcokreeft87
