### ISSUE TITLE
Session days for Las Vegas Grand Prix are incorrect

### ISSUE THREAD

**Issue by MauriceW67** [marcokreeft87/formulaone-card#315]
**Describe the bug**
When calculating the day for the various sessions of the Las Vegas Grand Prix to EU times, all days are shown as one too early (i.e. it says Thursday instead of Friday, etc.).

Secondary issue: There is no track map being displayed for the LV circuit.

**Expected behavior**
Session times showing the correct day.

**Comment by marcokreeft87** [comment]
The API does that. Can't do anything about ut sorry
