### ISSUE TITLE
Card doesn't exists in conditional card on Fully Kiosk Browser and phone

### ISSUE THREAD

**Issue by larsvdmanden** [marcokreeft87/formulaone-card#318]
Hi,

I had a good working custom:formulaone-card but I wanted to see the days till the next race changed with a Christmas countdown. The code below is working on my computer browser, but not on my phone or in Fully Kiosk browser (see screendumps). It's since I made a conditional card from it. What is going wrong?

type: custom:stack-in-card
parameters:
  scrollbar:
    hide: false
    draggable: true
    snapOnRelease: true
cards:
  - type: conditional
    conditions:
      - entity: input_boolean.f1_christmascountdown
        state: 'off'
    card:
      type: vertical-stack
      cards:
        - type: picture
          image: /local/images/f1.png
          tap_action:
            action: navigate
            navigation_path: /dashboard-tablet/f1
          card_mod:
            style: |
              ha-card {
              height: 20px;
              width: 75px;
              top: 35px;
              left: 0%;
              background: none;
              border: none;
              }
        - type: custom:formulaone-card
          card_type: countdown
          f1_font: true
          card_mod:
            style: |
              ha-card {
              height: 88px;
              width: 236px;
              font-size: 6px;
              left: 75px;
              top: -30px;
              }
          tap_action:
            action: navigate
            navigation_path: /tablet-living-room/f1-stats
  - type: conditional
    conditions:
      - entity: input_boolean.f1_christmascountdown
        state: 'on'
    card:
      show_state: true
      show_name: true
      camera_view: auto
      type: picture-entity
      entity: sensor.anniversary_christmas
      image: >-
        https://assets.editorial.aetnd.com/uploads/2009/10/christmas-gettyimages-184652817.jpg
      name: Dagentotkerst.nl
      theme: ios-dark-mode-blue-red-alternative
      card_mod:
        style: |
          ha-card {
            height: 100px !important;
            background-position: center center;
          }
  - initial_view: listWeek
    type: calendar
    entities:
      - calendar.feestdagen_in_nederland

![IMG_3534](https://github.com/marcokreeft87/formulaone-card/assets/58793484/7c478601-90a9-4427-8c60-b6e949cb9a7c)
![IMG_3533](https://github.com/marcokreeft87/formulaone-card/assets/58793484/89f93ae7-81b6-4c60-b49b-b311d1282cfb)

**Comment by marcokreeft87** [comment]
Hmm weird. The logo is there so it is doing something. I don't have the time till tomorrow to check for you so hold on

**Comment by larsvdmanden** [comment]
Many thanks!

The iOS app looks okay now, it might did need a restart. But on the Fully Kiosk app, the problem is still there after deleting the cache and restarting the app several times. As you can see exactly the same dashboard is working on a Chrome browser. The code I am using is also working on the tablet without the conditions, so it just appears on the Fire Tablet with the full kiosk app. 

<img width="529" alt="Scherm­afbeelding 2023-11-23 om 21 00 28" src="https://github.com/marcokreeft87/formulaone-card/assets/58793484/478d4d4a-eacd-4c78-9fec-d121b9b965d3">

**Comment by marcokreeft87** [comment]
@larsvdmanden  is your issue solved btw? Kinda forgot this issue xD

**Comment by larsvdmanden** [comment]
I don't know actually, it still says: Season is over. See you next year!

**Comment by marcokreeft87** [comment]
So it's working. Season over is another issue caused by the api

**Comment by larsvdmanden** [comment]
Now the api is working again and the countdown actually showing a countdown... the problem is back. On the pc it says 'error getting next race', whilst on the smartphone everything is fine. I really don't understand why it's behaving like this. It's exactly the same card/code on phone as on web. Do you have any idea?

<img width="458" alt="Screenshot 2024-03-08 at 21 45 18" src="https://github.com/marcokreeft87/formulaone-card/assets/58793484/d648e5aa-1843-4622-bdf3-3a350ab41bec">

**Comment by marcokreeft87** [comment]
> Now the api is working again and the countdown actually showing a countdown... the problem is back. On the pc it says 'error getting next race', whilst on the smartphone everything is fine. I really don't understand why it's behaving like this. It's exactly the same card/code on phone as on web. Do you have any idea?
> 
> <img width="458" alt="Screenshot 2024-03-08 at 21 45 18" src="https://github.com/marcokreeft87/formulaone-card/assets/58793484/d648e5aa-1843-4622-bdf3-3a350ab41bec">
> 

Because the card cached the data on the device. So it's different on each device

**Comment by larsvdmanden** [comment]
Oh, it's fully working now! I think it was a cache thing indeed. But the problem I had last year is solved as well lol. Happy!
