### ISSUE TITLE
Problem sensor

### ISSUE THREAD

**Issue by schumi2309** [marcokreeft87/formulaone-card#32]
![Capture d’écran 2022-12-19 à 12 57 22](https://user-images.githubusercontent.com/47976917/208421331-7c6cd712-db3c-4a62-8839-1822ffafa906.png)

But i have not problem in my sensor .

![Capture d’écran 2022-12-19 à 13 01 33](https://user-images.githubusercontent.com/47976917/208421654-6923da9d-01ca-4fee-9a14-00aac8719076.png)

?

**Comment by marcokreeft87** [comment]
It think your sensor isnt providing data. Can you check ?

**Comment by schumi2309** [comment]
Indeed, no data: unknown

What to do ?
I have already re-installed add-on, without success.

**Comment by marcokreeft87** [comment]
Ask the developers of the API :p

**Comment by schumi2309** [comment]
ok, thanks.
