### ISSUE TITLE
Start season and information

### ISSUE THREAD

**Issue by FoUStep** [marcokreeft87/formulaone-card#332]
Please start the season with the F1 calendar sooner. It's still saying: Season is over. See you next year.

Even though the season starts at the end of this month, so next year is already here. The calendar on the website is already updated with new info.

**Comment by marcokreeft87** [comment]
Please search for existing issues/discussions before posting a new one.

But the problem is the API. It's not providing the start time of the races

**Comment by FoUStep** [comment]
I've been looking for keywords such a Start season but could not find any matching results in the open and closed issues.

A suggestion could be to manually input the start of the season in an input script for a new year if the API does not give back any decent results.

**Comment by marcokreeft87** [comment]
Sorry guys, but the data of the current season is useless from the API. 
![image](https://github.com/marcokreeft87/formulaone-card/assets/10223677/91704959-b6c8-444a-81d3-baaa12582e96)
This of from last year
![image](https://github.com/marcokreeft87/formulaone-card/assets/10223677/b30d2e8a-f9bd-4108-9fdf-d260af9f976f)
This is from this year.

As you can see the practice times are gone and the qualifying.. I have to rewrite all the cards to be able to use this data and even than it won't be more than a glorified table without the practice sessions and stuff.

I will continue to check for updates. Lets hope this changes!

**Comment by yazz007** [comment]
As far as I understand, it can have a countdown at least, right?

**Comment by marcokreeft87** [comment]
Nope, because until what time will it count down to?

**Comment by marcokreeft87** [comment]
My countdown is working now. Seems like the api is updating a bit of data now
