### ISSUE TITLE
show_lastyears_result does not work in countdown card

### ISSUE THREAD

**Issue by Tagliax** [marcokreeft87/formulaone-card#339]
**Describe the bug**
show_lastyears_result has no effect on the countdown card and show just countdown.

**To Reproduce**

card_type: countdown
        f1_font: true
        show_lastyears_result: true
        countdown_type:
          - practice1
          - practice2
          - practice3
          - sprint
          - qualifying
          - race

**Expected behavior**
As documentation (Show the winner of last year (next_race, countdown))
The result of last season is shown

**Comment by marcokreeft87** [comment]
As long as the api doesn't return the correct data, I can't fix data related issues. Sorry.

Btw I think I've gotten the data between outages. So maybe it's a waiting game solution.

![Screenshot_20240302_165320_Home Assistant.jpg](https://github.com/marcokreeft87/formulaone-card/assets/10223677/f8ee760f-febe-4865-8e5c-86563233d063)

**Comment by Tagliax** [comment]
Yes, it only works on the next race card.
