### ISSUE TITLE
Card is still showing season is over, see you next year

### ISSUE THREAD

**Issue by Anonymouse0104** [marcokreeft87/formulaone-card#340]
**Describe the bug**

Card is still showing season is over, see you next year

**To Reproduce**
open the card 

**Screenshots**

![IMG_0825](https://github.com/marcokreeft87/formulaone-card/assets/92398953/b33c65b2-98c0-4f97-9be9-ed9527738619)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrone
 - Version of the card 1.8.9

**Smartphone (please complete the following information):**
 - Device: iPhone 15 PRO
 - OS: iOS 17.4

**Comment by marcokreeft87** [comment]
Because this is one of many of the same issues. You apparently didn't search existing issues
