### ISSUE TITLE
Dont work on old ios versions

### ISSUE THREAD

**Issue by Ayrex3424** [marcokreeft87/formulaone-card#344]
**Describe the bug**
It says custom element doesn't exist, but on pc it shows just normal!
**To Reproduce**
1. Go to your home Assistant on an ios device with ios 12.x.x or lower
2. See error

**Comment by marcokreeft87** [comment]
I don't have a Apple device, but this sounds like you need to Refresh the cache.
Has nothing to do with your old Apple device.
