### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'attributes')

### ISSUE THREAD

**Issue by WizBangCrash** [marcokreeft87/formulaone-card#35]
**Describe the bug**
Used HACS to install and created a schedule card:
```
type: custom:formulaone-card
card_type: schedule
sensor: sensor.formula_one_sensor_races
title: Schedule
date_locale: gb
```
Get the TypeError message:
```
TypeError: Cannot read properties of undefined (reading 'attributes')
```

I've checked everything is installed correctly and tried other card_types, but they all give the same error :-(

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 13.1
 - Browser [e.g. chrome, safari] Brave & Safari 
 - Version [e.g. 22] 2022.12.8

**Comment by marcokreeft87** [comment]
I think the date locale isn't correct. Try en_gb

**Comment by marcokreeft87** [comment]
Do you have the api integration installed? And what does the output of that say?

**Comment by WizBangCrash** [comment]
Hi @marcokreeft87,
I get the message:
```
2022-12-23 09:28:24.215 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration formulaone_api which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```
when I boot, but the integration does not show up in integrations view or the devices view.
There are also no other messages in the log.
I'll take a look at the formulate_api GitHub repo and see if others have the same issue as me.
Thanks

**Comment by WizBangCrash** [comment]
Turning on debug shows sensors are never updating and timing out.
Looking at https://github.com/delzear/hass-formulaoneapi I have just seen his message that the API is down while he is making big changes!

Thanks for your quick response. I will watch the api repo and wait for it to be working again :-)
