### ISSUE TITLE
Three issues

### ISSUE THREAD

**Issue by slingshot74** [marcokreeft87/formulaone-card#350]
Hi,

I have installed this nice integration. Really like it!
But I have three issues:
1. The countdown types I select.in the interface are not saved in the yaml. It's always the countdown the race
2. The next race only shows the circuit but no information about dates en times etc.
3. The results card only show the year and circuit.box but no result.

I can't find any errors in the logs.

![Screenshot_20240322_215655_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/da2bc48f-7135-4934-97a5-51210141305d)
![Screenshot_20240322_215727_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/21b2ce0e-1fd2-4c7e-8876-391eba35b1f9)

I hope someone can help to solve this.

Thank you very much!

**Comment by marcokreeft87** [comment]
1: Is that with the editor?
2: plz read the wiki on that

**Comment by slingshot74** [comment]
Hi,

1. In the editor I select them but they are not saved

![Screenshot_20240322_222634_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/8888c286-c477-477f-a111-557375e67416)
![Screenshot_20240322_222647_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/10a9029b-b485-4f4d-b727-540af291186e)

2. Where can I find that? Can you please share a link for me?

3.Of course will do and let you know. Will there be no error in the logs?

**Comment by marcokreeft87** [comment]
> Hi,
> 
> 1. In the editor I select them but they are not saved
> 
> ![Screenshot_20240322_222634_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/8888c286-c477-477f-a111-557375e67416)
> ![Screenshot_20240322_222647_Home Assistant](https://github.com/marcokreeft87/formulaone-card/assets/125136823/10a9029b-b485-4f4d-b727-540af291186e)
> 
> 2. Where can I find that? Can you please share a link for me?
> 
> 3.Of course will do and let you know. Will there be no error in the logs?

Sorry I meant the readme. Is on the startpage of the repo.

Ah yeah that's a bug I think. Please use the yaml mode for now.

**Comment by slingshot74** [comment]
Hi,

1. Done, thanks
2. I did read that but couldn't find but it starts working now.
3. It's working now

2 and 3 probably an issue with the API I think.

Thanks for your support!

**Comment by marcokreeft87** [comment]
YW
