### ISSUE TITLE
FR: Possibility to show only date/time for next race in the NextRace or Countdown card.

### ISSUE THREAD

**Issue by jimz011** [marcokreeft87/formulaone-card#351]
Would it be possible to implement features that will change how information is shown in a card?

Below is an example of what the card height should be, I would love to be able to add the time to this card without it getting bigger (meaning it would better fit as a button on the frontpage sitting with other buttons).

![image](https://github.com/marcokreeft87/formulaone-card/assets/47046878/4517aa61-b595-4c4d-828c-ad2588579a5c)

It would actually even be better if it would show the flag and then the name of the race day (e.g. Next Sunday at 17.00 or e.g. Sunday 12-04-2024 at 17.00).

**Comment by marcokreeft87** [comment]
Your second suggestion wouldn't be that much smaller. I don't see a good way to make it smaller without losing data.

Could you provide more examples of how you want to see it?

**Comment by jimz011** [comment]
Hi, thanks for replying. I was thinking of something like this (which would then be displayed as a button on the front page for example).

A bit like the countdown, but then with date and time instead (I find it easier to read than 120h until next race).

My editing skills aren't great, but here is an example:
![image](https://github.com/marcokreeft87/formulaone-card/assets/47046878/f14b6b88-165a-4601-9b21-913e5e8f51cd)

**Comment by marcokreeft87** [comment]
Ah like that. That block with the date in it shouldn't be visible in the next race card so that's kind of a bug.

Tbf the next race card is like a forgotten child haha. Was thinking of removing it.

Let's see what I can do. But have to find the time...

**Comment by jimz011** [comment]
No hurry, I was just wondering if you would be able to make something like that. Before I could simply use the sensors from the formulaoneapi but that no longer works.

Thanks for the input

**Comment by marcokreeft87** [comment]
You could use the calendar integration for that

**Comment by marcokreeft87** [comment]
I've added the option. See next_race_display in the readme
