### ISSUE TITLE
FR: Have the schedule card hide past races when using "row_limit" 

### ISSUE THREAD

**Issue by julianrinaldi** [marcokreeft87/formulaone-card#358]
When using the "row_limit" option on the schedule card, it would be nice if it hid past races, our at least had the option to hide past races. It seems pretty pointless to even have the ability to limit the rows without that option.

**Comment by julianrinaldi** [comment]
I missed that. Thanks.

**Comment by marcokreeft87** [comment]
I was looking through the docs and it's not in there so not your fault bro.
