### ISSUE TITLE
Error in Monaco results

### ISSUE THREAD

**Issue by steluci** [marcokreeft87/formulaone-card#360]
Hello

The Monaco results show 71 point for Hamilton.
This also impact the drivers ranking, showing Hamilton at 106 points instead of 42.

I hope this helps

![f1](https://github.com/marcokreeft87/formulaone-card/assets/112645267/a179b0cb-6cb9-499c-ae60-010f2524d399)

**Comment by marcokreeft87** [comment]
The card doesn't provide the data it 9nly displays it.
