### ISSUE TITLE
Error in driver standings card

### ISSUE THREAD

**Issue by marc115uk** [marcokreeft87/formulaone-card#370]
Version 1.9.3 
Drivers standings card does not seem to work with the added tag of 
standings:
  show_flag: true

currently have 

type: custom:formulaone-card
card_type: driver_standings
title: Driver Standings
show_carnumber: true
standings:
  show_flag: true
  show_team: true
  show_teamlogo: true
f1_font: true

if I remove the line show flag it works, with that line in I get error getting standing message

**Comment by marcokreeft87** [comment]
If you add 

```show_refresh: true```

You get a refresh button. That should help.

The new api had an error in the driver standings

**Comment by JohnOnline88** [comment]
Same issue here. 

`show_flag: true` results in the error "! Error getting standings !"
`show_flag: false` results in a working card

The use of `show_team` and `show_teamlogo` has no impact on getting the standings and can be used as normal.

**Comment by fanaticDavid** [comment]
I can confirm the observations above.

I tried adding `show_refresh: true` and the refresh button does appear, but it doesn't seem to be interactive. The cursor doesn't change when hovering over it, and clicking on it doesn't seem to do anything either.

**Comment by marcokreeft87** [comment]
Version 1.9.4 should fix it.

**Comment by marc115uk** [comment]
> Version 1.9.4 should fix it.

Seems to have fixed it. Thanks :)
