### ISSUE TITLE
Support daylight saving time

### ISSUE THREAD

**Issue by ArthurGarnier** [marcokreeft87/formulaone-card#384]
**Describe the bug**
Time of the race is shifted by one hour during winter time in France. 
For example sprint datetime today in France was 3PM and card displayed 2PM.

**To Reproduce**
Set date_locale to fr ?

**Expected behavior**
display the right time for the events.

**Screenshots**
![Screenshot_20241130_154610_Home Assistant](https://github.com/user-attachments/assets/e5b1bc81-ada1-4a02-a75c-cef811cdca7e)

**Smartphone (please complete the following information):**
 - Device: Galaxy S24 Ultra
 - OS: Android 14
 - Browser : N/A (Home assistant app)
 - Version: 2024.10.3

**Comment by marcokreeft87** [comment]
The times are coming from an api. The translation to local time is done by home assistant. I don't think I can fix this within the card

**Comment by ArthurGarnier** [comment]
In fact it looks like a bug in the API. For Qatar the card report 18

**Comment by marcokreeft87** [comment]
Than I certainly can't do anything about it. Sorry
