### ISSUE TITLE
getCountryFlag does not return correct URL

### ISSUE THREAD

**Issue by fmeus** [marcokreeft87/formulaone-card#45]
**Describe the bug**
The function getCountryFlag does not return the correct URL for flag, except for USA and UEA 9 (the hardcoded exceptions). 
The URL is now constructed as https://flagcdn.com/w40/bahrain.png, if should be https://flagcdn.com/w40/bh.png

**To Reproduce**
To reproduce simple create the documented card for the next race and the last race. The first race being in Bahrain displays a broken link, the last race in Abu Dhabi displays the correct flag.

**Expected behavior**
Correct URLs for every country

**Screenshots**
No flag for Bahrain
<img width="567" alt="Bahrain" src="https://user-images.githubusercontent.com/743402/210174434-0704ea3a-76ae-4a8e-8bad-a625a2658279.png">

Correct flag for Abu Dhabi
<img width="538" alt="Abu Dhabi" src="https://user-images.githubusercontent.com/743402/210174448-992560a2-8815-4d6d-923b-358fdceee572.png">

**Desktop (please complete the following information):**
 - not browser specific.

**Smartphone (please complete the following information):**
 - not browser specific.

**Additional context**
The function appears the expect country codes, whereas the country field contains (partial) country names (Netherlands instead of NL, Bahrain instead of BH).

**Comment by fmeus** [comment]
Thanks for the quick fix, but this fix seems to have broken the last result card (or maybe related to the coded exceptions)

![image](https://user-images.githubusercontent.com/743402/210179635-06e1708c-33f7-423d-b534-a124306d8d24.jpeg)

**Comment by marcokreeft87** [comment]
You are right! Fix incoming :)

**Comment by fmeus** [comment]
Version 2.2.3 resolved the issue. Thanks again!
