### ISSUE TITLE
Date Format for Schedule

### ISSUE THREAD

**Issue by schmuy** [marcokreeft87/formulaone-card#67]
I'd love to change the date format for the schedule

**Comment by marcokreeft87** [comment]
Check the Readme. It's already an option

**Comment by schmuy** [comment]
I see the date_locale option.  I was hoping to be able to manually change the schedule to MMM DD rather than what gets preset by the locale

**Comment by marcokreeft87** [comment]
Nope sorry, this is way more error safe
