### ISSUE TITLE
Another 'TypeError: Cannot read properties of undefined' error

### ISSUE THREAD

**Issue by JoostAB** [marcokreeft87/formulaone-card#92]
**Describe the bug**
Defined the default cards using your examples. All work except for the results and countdown card. They only render a red card with 
a 'TypeError: Cannot read properties of undefined (reading 'render')' error.

**To Reproduce**
Just installed 0.3.5 card and defined them on my dashboard

**Expected behavior**
Nice cards :)

**Screenshots**
![image](https://user-images.githubusercontent.com/16137715/213490623-965c664c-6384-4cb3-b596-e302f2279a4f.png)

![image](https://user-images.githubusercontent.com/16137715/213490758-ad8d0d92-c802-4e10-b729-6463df846cc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro 22H2
 - Browser Chrome
 - Version 109.0.5414.75

Same goes for my phone, therefore:
**Smartphone (please complete the following information):**
 - Device: Pixel 6 pro
 - OS: Duh... ;) Android 13
 - Browser chrome and companion app
 - Version latest

**Additional context**
I did have the formula-one-api integration installed before. But I read that this card was no longer depending on that api so I uninstalled it.

BTW, even without the results and countdown card... Amazing job! Thx!

**Comment by marcokreeft87** [comment]
Try it with version 0.5

**Comment by JoostAB** [comment]
Wow! That's fast! :)
Version 3.5 was the latest according to HACS... But it is fixed. Thx

**Comment by marcokreeft87** [comment]
Yeah HACS caches a lot. I told them, but the creator won't listen
