### ISSUE TITLE
Hide flag and title

### ISSUE THREAD

**Issue by Tontze** [marcokreeft87/formulaone-card#95]
Would like to have a option to disable title for better card stacking. See image. 

![image](https://user-images.githubusercontent.com/28216916/213880981-be13d596-84e9-4560-b8c7-71c5e9f27eb4.png)

Awesome work, btw :D

**Comment by marcokreeft87** [comment]
Have you tried not passing a title?

**Comment by Tontze** [comment]
Yes, m talking about flag and race name :)
