### ISSUE TITLE
Team icons

### ISSUE THREAD

**Issue by hmmbob** [marcokreeft87/formulaone-card#97]
**Is your feature request related to a problem? Please describe.**
Feat request: would it be possible to also have the team icons in the constructors overview, just like the flag of the driver?
And possible, configurable, also in the other overviews?

**Have you tried if it is already a feature? Have you checked the wiki?**
Seems not to exist yet

**Describe the solution you'd like**
A small team icon added to the overview

**Describe alternatives you've considered**
N/a

**Additional context**
![image](https://user-images.githubusercontent.com/33529490/213904530-da7aff47-44d6-4ddf-bf90-f046dce08ccf.png)

**Comment by marcokreeft87** [comment]
Note to self: https://www.formula1.com/content/dam/fom-website/teams/2023/mercedes-logo.png.transform/2col-retina/image.png

**Comment by marcokreeft87** [comment]
Ok I have to code to display the images. All I need is transparant team images @hmmbob . Can you help search for them?

**Comment by hmmbob** [comment]
Sure, but won't be before tonight or so

**Comment by hmmbob** [comment]
https://www.pngwing.com/en/search?q=f1+Logo

**Comment by hmmbob** [comment]
Or, from wiki: https://www.google.com/search?q=transparent+f1+team+logos+site%3Awikimedia.org

**Comment by hmmbob** [comment]
Or best: F1.com :)

https://www.formula1.com/en/teams.html

**Comment by marcokreeft87** [comment]
> Or best: F1.com :)
> 
> https://www.formula1.com/en/teams.html

Those are not transparant. Thats fine on white backgrounds, but looks like shit on dark mode for example

**Comment by hmmbob** [comment]
> > Or best: F1.com :)
> > https://www.formula1.com/en/teams.html
> 
> Those are not transparant. Thats fine on white backgrounds, but looks like shit on dark mode for example

Damn, I was triggered by the "transparant png blocks" in chrome but those are only for the surroundings indeed. My bad.

**Comment by marcokreeft87** [comment]
Didnt mean to close it. I tried transparant logos with base64 strings in the code. But that made the source over 800kb. 
So back to using the team logos from the f1 site. And trying to fix it

**Comment by marcokreeft87** [comment]
![image](https://user-images.githubusercontent.com/10223677/213942984-0c1d2bce-eaf8-4b42-9e71-d70dc1239d9b.png)

Not bad right?

**Comment by hmmbob** [comment]
Looks great!

**Comment by EvertJob** [comment]
@hmmbob what plug-in are you using to showing the F1 in tabs as in you’re first post?

**Comment by hmmbob** [comment]
The tabbed card, mentioned in the thread by others 

https://github.com/kinghat/tabbed-card
