### ISSUE TITLE
tap_action on card

### ISSUE THREAD

**Issue by ChrisPolewiak** [marcokreeft87/formulaone-card#98]
Please add a tap_action which allow to navigate from main page with card_type: countdown to other page with more data.

Thanks

**Comment by marcokreeft87** [comment]
You can config the card to do that with 

```image_clickable: true```

**Comment by JoostAB** [comment]
That does not work with the count down card. And I think Chris means he wants to navigate to a custom URL, not only wikipedia.

**Comment by ChrisPolewiak** [comment]
thanks for the clarification - the point is that by clicking I would go to another dashboard in HA where I have more details ...
